name: bottom_sheet_item_selector
description: "A Flutter package that provides a customizable bottom sheet widget for selecting items, supporting both single and multiple selections."
version: 0.0.1
homepage: https://github.com/sachincvn/bottom_sheet_item_selector
repository: https://github.com/sachincvn/bottom_sheet_item_selector
issue_tracker: https://github.com/sachincvn/bottom_sheet_item_selector/issues

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
